# fly.toml app configuration file generated for lumi-server on 2024-10-18T05:44:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lumi-server'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
